name: cred-score
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow==1.27.0
    - numpy==1.23.1
    - matplotlib==3.5.2
    - pandas==1.4.3
    - scikit-learn==1.1.1
    - seaborn==0.11.2
    - jupyter==1.0.0
    
