name: mlflow_2
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - mlflow==1.27.0
    - numpy==1.21.6
    - matplotlib==3.5.2
    - pandas==1.3.5
    - scikit-learn==1.0.2
    
